image: Visual Studio 2017

environment:
  matrix:
  - COMPILER: MinGW
    QT_PATH: C:\Qt\5.12\mingw73_32
  - COMPILER: MSVC2017
    QT_PATH: C:\Qt\5.12\msvc2017

before_build:
  - set BUILD_DIR=%cd%
  - set PATH=%QT_PATH%\bin;C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0\mingw32\bin;%PATH%
  - if %COMPILER% == MinGW if not exist "C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0" md "C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0"
  - if %COMPILER% == MinGW cd C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0
  - if %COMPILER% == MinGW if not exist "mingw32" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z" -FileName "mingw32.7z"
  - if %COMPILER% == MinGW if exist "mingw32.7z" 7z x -y "mingw32.7z" > NUL
  - if %COMPILER% == MinGW cd %BUILD_DIR%

build_script:
  - mkdir build
  - cd build
  - if %COMPILER% == MSVC2017 cmake .. "-DCMAKE_PREFIX_PATH=%QT_PATH%"
  - if %COMPILER% == MinGW cmake .. -G "MinGW Makefiles" "-DCMAKE_PREFIX_PATH=%QT_PATH%" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
  - cmake --build .
