image:
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
  - COMPILER: MinGW
    QT_PATH: C:\Qt\5.13\mingw73_32
  - COMPILER: MSVC17
    QT_PATH: C:\Qt\5.13\msvc2017
  - COMPILER: MSVC19
    QT_PATH: C:\Qt\5.15\msvc2019

matrix:
  exclude:
    - COMPILER: MinGW
      image: Visual Studio 2019
    - COMPILER: MSVC17
      image: Visual Studio 2019
    - COMPILER: MSVC19
      image: Visual Studio 2017

before_build:
for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
          COMPILER: MinGW
    before_build:
    - set BUILD_DIR=%cd%
    - set PATH=C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0\mingw32\bin;%PATH%
    - if not exist "C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0" md "C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0"
    - cd C:\mingw-w64\i686-8.1.0-posix-seh-rt_v6-rev0
    - if not exist "mingw32" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z" -FileName "mingw32.7z"
    - if exist "mingw32.7z" 7z x -y "mingw32.7z" > NUL
    - cd %BUILD_DIR%

build_script:
  - set PATH=%QT_PATH%\bin;%PATH%
  - mkdir build
  - cd build
  - if %COMPILER% == MSVC17 cmake .. "-DCMAKE_PREFIX_PATH=%QT_PATH%" -A Win32
  - if %COMPILER% == MSVC19 cmake .. "-DCMAKE_PREFIX_PATH=%QT_PATH%" -A Win32
  - if %COMPILER% == MinGW cmake .. -G "MinGW Makefiles" "-DCMAKE_PREFIX_PATH=%QT_PATH%" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
  - if %COMPILER% == MSVC17 cmake --build .
  - if %COMPILER% == MSVC19 cmake --build .
  - if %COMPILER% == MinGW cmake --build . -- -j
  - bin\\fishing-time_test
