name: macOS nightly

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  macOS-gcc-build-nightly:
    runs-on: macOS-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc
      run: |
        brew install gcc@9
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
      env:
        CC: gcc-9
        CXX: g++-9
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
  macOS-clang-build-nightly:
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
