name: Build application

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install g++-9 qt5-default
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install clang-8 qt5-default
    - name: Build application
      run: |
        mkdir build
        cd build
        CC="clang-8" CXX="clang++-8" cmake ..
        cmake --build . -- -j
  macOS-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        brew install qt
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt)/lib/cmake/Qt5
        cmake --build . -- -j
