name: Nightly

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  ubuntu-gcc-build-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
  ubuntu-clang-build-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install clang
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt update
        sudo apt install clang-9
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
      env:
        CC: clang-9
        CXX: clang++-9
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
  macOS-gcc-build-nightly:
    runs-on: macOS-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install gcc
      run: |
        brew install gcc@9
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
      env:
        CC: gcc-9
        CXX: g++-9
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
  macOS-clang-build-nightly:
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j
    - name: Run tests
      run: |
        cd build
        ./bin/fishing-time_test
  windows-msvc-build-nightly:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: win64_msvc2017_64
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Run tests
      run: |
        cd build
        bin\\fishing-time_test
  windows-mingw-build-nightly:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_version: ['5.12.6', '5.14.1']
    steps:
    - uses: actions/checkout@v1
    - name: Install MSYS2
      uses: numworks/setup-msys2@v1
    - name: Install gcc
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc
    - name: Install Qt
      uses: aobolensk/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: win64_mingw73
    - name: Build application
      run: |
        mkdir build
        cd build
        cmake .. -G"MSYS Makefiles"
        cmake --build . -- -j
      env:
        CC: gcc
        CXX: g++
    - name: Run tests
      run: |
        cd build
        bin\\fishing-time_test
